spring:
  datasource:
    username: root
    password: as661778
    url: jdbc:hive2://localhost:10000/orcdata
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB  #单个文件最大大小
      max-request-size: 6000MB #上传数据总大小
mybatis-plus:
  mapper-locations: mapper/**/*.xml

server:
  port: 9091